services:
    api:
        build:
          context: .
          dockerfile: ./Dockerfile
        environment:
          - ConnectionStrings__DefaultConnection=Server=localhost,1450;Database=ToDo;User Id=sa;Password=Kimdien1105@;TrustServerCertificate=True
          - ASPNETCORE_ENVIRONMENT=Development
        ports:
          - "5072:8080"
        depends_on:
          - db
       

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        container_name: sqlserver-db
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_PID=Developer
          - MSSQL_SA_PASSWORD=Kimdien1105@
        ports:
          - "1450:1433"
        volumes:
          - sql-data:/var/opt/mssql
        restart: unless-stopped
volumes:
  sql-data: